name: Build Core Container AMD64

on:
  workflow_dispatch: {}
  #push:
  #  branches:
  #    - main

jobs:
  build_core:
    name: Build Core Container
    uses: ./.github/workflows/build_container.yml
    secrets: inherit
    with:
      image_name: 'vooplv/webcontainer'
      image_tag: 'core'
      dockerfile_path: ${{ github.workspace }}

