name: Build_Containers
run-name: Build Containers AMD64

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build_core_amd64:
    name: Build Core Container AMD64
    uses: ./.github/workflows/build_container_template.yml
    secrets: inherit
    with:
      image_name: 'webcontainer'
      image_tag: 'dev'
      type: 'core'
      runner: ${{ vars.RUNNER }}

  build_nginx_amd64:
    name: Build Nginx Container AMD64
    needs: build_core_amd64
    uses: ./.github/workflows/build_container_template.yml
    secrets: inherit
    with:
      image_name: 'webcontainer'
      image_tag: 'dev'
      type: 'nginx'
      runner: ${{ vars.RUNNER }}
      core_image: 'vooplv/webcontainer:core-dev'

  build_openresty_amd64:
    name: Build Openresty Container AMD64
    needs: build_core_amd64
    uses: ./.github/workflows/build_container_template.yml
    secrets: inherit
    with:
      image_name: 'webcontainer'
      image_tag: 'dev'
      type: 'openresty'
      runner: ${{ vars.RUNNER }}
      core_image: 'vooplv/webcontainer:core-dev'
      
