name: Build Core Container AMD64

on:
  workflow_dispatch: {}
  #push:
  #  branches:
  #    - main

jobs:
  build_core:
    name: Build Core Container
    uses: ./.github/workflows/build_container_template.yml
    secrets: inherit
    with:
      image_name: 'webcontainer'
      image_tag: 'dev'
      type: 'core'

