name: Build and Deploy

wotkflow_dispatch: {}
on:
  push:
    branches: main

jobs:
  container:
    name: Build and Push container
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build Container
        run: |
          chmod -R 755 build.sh
          sh build.sh
      - name: Deploy to Docker Hub
        run: |
          docker push vooplv/webcontainer:core
          docker push vooplv/webcontainer:nginx
          docker push vooplv/webcontainer:openresty